General Hot Fixes
yarrm80s/orpheusdl-soundcloud pull request #2
Opened 2022-05-12 16:24 UTC by mexsana123

These should fix some of the issues that I've had using the Soundcloud module, although I'm a bit skeptical at Line 125. It works perfectly fine for now.

2022-05-12 21:28 UTC, Dniel97 requested changes
Thanks for the PR!
I have some comments about you PR:

1. The variable `data` can be an empty dictionary so this will throw an error:
```python 
track_number = int(list(data.keys()).index(track_id))+1,
```
2. Is `created_at` always present? If unsure also implement a fallback just to be sure
```python
release_date = track_data['created_at'].split('T')[0]
```
3. About L125, the album_id is used to show it after the album title in the CMD, so I would prefer to ignore it and set to `''` it - but that's a personal preference

2022-05-17 08:56 UTC, mexsana123 commented
I've applied some of the changes that you've recommend. I'll also like to go ahead and explain what L125 is supposed to do. When the interface calls from Soundcloud, It'll return a json with the track_id being a value, which when it tries to parse it will return an error and this is caused due to Orpheus returning an empty album_id. 
```py
    def get_album_info(self, album_id, data):
        playlist_data = data[album_id]
```
Thus adding the `track_id` in `album_id` will correctly return the json array without any issues.

2022-05-17 09:07 UTC, yarrm80s commented
@mexsana123 which JSON data and what error are you talking about?

2022-05-17 16:14 UTC, Dniel97 approved these changes

2022-05-17 16:15 UTC, merged